# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' imports genotypeMatrix
#' 
#' @param fileName location of plink binary file
#' @param N number of subjects
#' @param P number of SNPs
#' @param col_skip_pos which variants to skip
#' @param col_skip which variants to skip
#' @param keepbytes which bytes to keep
#' @param keepoffset the offset
#' @param fillmissing whether to fillin missing cells
#' @return RcppArmadillo genotype matrix
#' 
genotypeMatrix <- function(fileName, N, P, col_skip_pos, col_skip, keepbytes, keepoffset, fillmissing) {
    .Call('_penRegSum_genotypeMatrix', PACKAGE = 'penRegSum', fileName, N, P, col_skip_pos, col_skip, keepbytes, keepoffset, fillmissing)
}

#'normalize genotype matrix
#'
#'@param genotypes RcppArmadillo genotype matrix
#'@return vector of standard deviations
#'
normalize2 <- function(genotypes) {
    .Call('_penRegSum_normalize2', PACKAGE = 'penRegSum', genotypes)
}

